runtime: go111
instance_class: F1

automatic_scaling:
  min_pending_latency: 50ms
  max_pending_latency: 500ms

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  SELF_HOST: 'blynk-proxy.appspot.com'
